name: RestrictiveArmor
version: ${version}
main: me.techchrism.restrictivearmor.RestrictiveArmor
author: Techdoodle
api-version: 1.19
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.0
commands:
  getitems:
  plshelpme:
    